apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  labels:
    app: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
          ports:
            - containerPort: 9200
          env:
            - name: ES_JAVA_OPTS
              value: -Xms1g -Xmx1g
            - name: discovery.type
              value: single-node
---
apiVersion: v1
kind: Service
metadata:
  name: elastic
spec:
  selector:
    app: elastic
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.14.0
          ports:
            - containerPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.16.1
          command: ["logstash -f /config-dir/kafka-pipeline.conf"]
          volumeMounts:
            - name: config-dir
              mountPath: /config-dir
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline/
      volumes:
        - name: config-dir
          emptyDir: ./logstash/config
        - name: pipeline
          emptyDir: ./logstash/pipeline/

---
apiVersion: v1
kind: logstash
metadata:
  name: logstash
spec:
  selector:
    app: logstash


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
        - name: filebeat
          image: bargenson/filebeat
          volumeMounts:
            - name: filebeat-dir
              mountPath: /tmp/docker.sock
          env:
            - name: LOGSTASH_HOST
              value: logstash
            - name: LOGSTASH_PORT
              value: 5044
            - name: SHIPPER_NAME
              value: Mauxilium
      volumes:
        - name: filebeat-dir
          emptyDir: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: filebeat
spec:
  selector:
    app: filebeat
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601

