version: '3.1'

services:
  layer:
    image: layer:1.0.0
    ports:
      - 8081:8080
      - 50501:50501
    environment:
      LAYER_NAME: layer
      DEST_LAYER: collector:8081
    depends_on: 
      - "zipkin"

  collector:
    image: collector:1.0.0
    ports:
      - 50502:50502
    environment:
      LAYER_NAME: collector
    depends_on: 
      - "zipkin"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
