version: '3.1'

services:
  layer1:
    image: layer:1.0.0
    ports:
      - 8081:8080
    environment:
      LAYER_NAME: layer1
      DEST_LAYER: layer2:8082

  layer2:
    image: layer:1.0.0
    ports:
      - 8082:8080
    environment:
      LAYER_NAME: layer2
      DEST_LAYER: layer3:8083

  layer3:
    image: layer:1.0.0
    ports:
      - 8083:8080
    environment:
      LAYER_NAME: layer3
      DEST_LAYER: collector:8084
      
  collector:
    image: collector:1.0.0
    ports:
      - 8084:8081
    environment:
      LAYER_NAME: collector

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
